---
abstract: 'testing TCP program'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TCP
no_index:
  directory:
    - inc
    - t
requires:
  IO::Socket::INET: 1.31
  Params::Validate: 0.91
  Sub::Exporter: 0.979
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
