---
abstract: 'testing TCP program'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-TCP
no_index:
  directory:
    - inc
    - t
requires:
  IO::Socket::INET: 1.31
  Params::Validate: 0.91
  perl: 5.8.0
version: 0.01
